import tomllib
from pathlib import Path

import pytest

from breakroom.construction import (
    ConstructionError,
    Floor,
    RoomType,
    Tower,
    encounter_odds,
    load_room_types,
    place_room,
)
from breakroom.worldstate import ValidationError

REPO_ROOT = Path(__file__).resolve().parent.parent
ROOM_TYPES_DIR = REPO_ROOT / "data" / "room-types"


def assert_validation_source(error: ValidationError, source: Path, detail: str) -> None:
    relative = source.resolve().relative_to(REPO_ROOT.resolve(), walk_up=True)
    assert str(error) == f"{relative}: {detail}"
    assert (REPO_ROOT / relative).resolve() == source.resolve()

# Hand-written worked-example table for encounter_odds, pinned from the issue #21 spec
# (same room, same floor, adjacent floor, otherwise) rather than generated by running
# the implementation.
ENCOUNTER_ODDS_WORKED_EXAMPLES = [
    {
        "description": "same room on the same floor",
        "room_a": "break-room",
        "floor_a": 1,
        "room_b": "break-room",
        "floor_b": 1,
        "expected": 1.0,
    },
    {
        "description": "different rooms on the same floor",
        "room_a": "break-room",
        "floor_a": 1,
        "room_b": "open-office",
        "floor_b": 1,
        "expected": 0.4,
    },
    {
        "description": "different rooms one floor apart, counting up",
        "room_a": "server-closet",
        "floor_a": 2,
        "room_b": "lobby",
        "floor_b": 3,
        "expected": 0.1,
    },
    {
        "description": "different rooms one floor apart, counting down",
        "room_a": "lobby",
        "floor_a": 3,
        "room_b": "server-closet",
        "floor_b": 2,
        "expected": 0.1,
    },
    {
        "description": "different rooms two floors apart",
        "room_a": "server-closet",
        "floor_a": 1,
        "room_b": "executive-suite",
        "floor_b": 3,
        "expected": 0.0,
    },
    {
        "description": "different rooms far apart in the tower",
        "room_a": "mailroom",
        "floor_a": 1,
        "room_b": "gym",
        "floor_b": 10,
        "expected": 0.0,
    },
]


def test_committed_catalog_has_at_least_fifteen_types_each_with_a_storylet_hook() -> None:
    catalog = load_room_types(ROOM_TYPES_DIR)

    assert len(catalog) >= 15
    for room_type in catalog.values():
        assert len(room_type.storylet_hooks) >= 1


def test_committed_catalog_ids_match_filenames() -> None:
    for path in ROOM_TYPES_DIR.glob("*.toml"):
        raw = tomllib.loads(path.read_text())
        assert raw["id"] == path.stem


def test_load_room_types_rejects_missing_field(tmp_path: Path) -> None:
    (tmp_path / "broken.toml").write_text(
        'id = "broken"\nname = "Broken"\ncapacity = 1\nassignable = true\nslots = 1\n',
        encoding="utf-8",
    )

    with pytest.raises(ConstructionError, match="broken.toml: missing storylet_hooks"):
        load_room_types(tmp_path)


@pytest.mark.parametrize("room_id", [7, ""])
def test_load_room_types_rejects_invalid_id(tmp_path: Path, room_id: object) -> None:
    (tmp_path / "broken.toml").write_text(
        f'id = {room_id!r}\nname = "Broken"\ncapacity = 1\nassignable = true\n'
        'slots = 1\nstorylet_hooks = ["room:broken"]\n',
        encoding="utf-8",
    )

    with pytest.raises(ValidationError) as exc_info:
        load_room_types(tmp_path)
    assert_validation_source(
        exc_info.value,
        tmp_path / "broken.toml",
        "id must be a non-empty string",
    )


@pytest.mark.parametrize("slots", ['"2"', "true"])
def test_load_room_types_rejects_invalid_slots(tmp_path: Path, slots: str) -> None:
    (tmp_path / "broken.toml").write_text(
        'id = "broken"\nname = "Broken"\ncapacity = 1\nassignable = true\n'
        f"slots = {slots}\nstorylet_hooks = [\"room:broken\"]\n",
        encoding="utf-8",
    )

    with pytest.raises(ValidationError) as exc_info:
        load_room_types(tmp_path)
    assert_validation_source(
        exc_info.value,
        tmp_path / "broken.toml",
        "slots must be an integer",
    )


def test_load_room_types_accepts_valid_room_type(tmp_path: Path) -> None:
    (tmp_path / "valid.toml").write_text(
        'id = "valid-room"\nname = "Valid Room"\ncapacity = 4\nassignable = true\n'
        'slots = 2\nstorylet_hooks = ["room:valid-room"]\n',
        encoding="utf-8",
    )

    assert load_room_types(tmp_path) == {
        "valid-room": RoomType(
            id="valid-room",
            name="Valid Room",
            capacity=4,
            assignable=True,
            slots=2,
            storylet_hooks=("room:valid-room",),
        )
    }


def test_load_room_types_rejects_empty_storylet_hooks(tmp_path: Path) -> None:
    (tmp_path / "broken.toml").write_text(
        'id = "broken"\nname = "Broken"\ncapacity = 1\nassignable = true\nslots = 1\n'
        "storylet_hooks = []\n",
        encoding="utf-8",
    )

    with pytest.raises(
        ConstructionError, match="broken.toml: storylet_hooks must be a non-empty list"
    ):
        load_room_types(tmp_path)


def test_load_room_types_rejects_duplicate_id(tmp_path: Path) -> None:
    body = (
        'id = "dup"\nname = "Dup"\ncapacity = 1\nassignable = true\nslots = 1\n'
        'storylet_hooks = ["room:dup"]\n'
    )
    (tmp_path / "first.toml").write_text(body, encoding="utf-8")
    (tmp_path / "second.toml").write_text(body, encoding="utf-8")

    with pytest.raises(ConstructionError, match="second.toml: duplicate room type id dup"):
        load_room_types(tmp_path)


def test_place_room_rejects_overfilled_floor() -> None:
    tower = Tower(floors={1: Floor(number=1, max_slots=2)})
    room_type = RoomType(
        id="open-office",
        name="Open Office",
        capacity=12,
        assignable=True,
        slots=3,
        storylet_hooks=("room:open-office",),
    )

    with pytest.raises(ConstructionError, match="exceeds max_slots"):
        place_room(tower, floor_number=1, slot_id="a", room_type=room_type)


def test_place_room_rejects_duplicate_slot() -> None:
    tower = Tower(floors={1: Floor(number=1, max_slots=5)})
    room_type = RoomType(
        id="private-office",
        name="Private Office",
        capacity=1,
        assignable=True,
        slots=1,
        storylet_hooks=("room:private-office",),
    )
    tower = place_room(tower, floor_number=1, slot_id="a", room_type=room_type)

    with pytest.raises(ConstructionError, match="slot a already occupied"):
        place_room(tower, floor_number=1, slot_id="a", room_type=room_type)


def test_place_room_rejects_undefined_floor() -> None:
    tower = Tower(floors={})
    room_type = RoomType(
        id="lobby",
        name="Lobby",
        capacity=15,
        assignable=False,
        slots=2,
        storylet_hooks=("room:lobby",),
    )

    with pytest.raises(ConstructionError, match="floor 3: not defined"):
        place_room(tower, floor_number=3, slot_id="a", room_type=room_type)


def test_place_room_accepts_legal_build_and_tracks_occupied_slots() -> None:
    tower = Tower(floors={1: Floor(number=1, max_slots=4)})
    room_type = RoomType(
        id="private-office",
        name="Private Office",
        capacity=1,
        assignable=True,
        slots=2,
        storylet_hooks=("room:private-office",),
    )

    tower = place_room(tower, floor_number=1, slot_id="a", room_type=room_type)
    assert tower.occupied_slots(1) == 2

    tower = place_room(tower, floor_number=1, slot_id="b", room_type=room_type)
    assert tower.occupied_slots(1) == 4


def test_encounter_odds_matches_hand_written_worked_example_table() -> None:
    for case in ENCOUNTER_ODDS_WORKED_EXAMPLES:
        actual = encounter_odds(case["room_a"], case["floor_a"], case["room_b"], case["floor_b"])
        assert actual == pytest.approx(case["expected"]), case["description"]
